# Generated by Django 4.2 on 2024-09-15 08:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0002_alter_climatologia_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climatologia',
            name='fecha',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
    ]
